---
title: "Assignment 7"
author: "Jacob Farmer"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    numbered_sections: true
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
robotstxt::paths_allowed(
  paths = "/fsb/directory/",
  domain = "miamioh.edu",
  bot = "*"
)
```

```{r}
dept_names = c('Accountancy', 'Economics', 'Entrepreneurship', 'Finance',
               'Information%20Systems%20%26%20Analytics', 'Marketing', 'Management')

scrape_fsb_directory = function(abbrv){
  directory_url = paste0(
    'https://miamioh.edu/fsb/directory/?up=/query/all/all/', abbrv, '/all'
  )
  
  webpage = rvest::read_html(directory_url)
  
  webpage |> rvest::html_elements("td:last-child strong a") -> name_links
  name_links |> rvest::html_element(xpath = "./text()") |> rvest::html_text2() |> stringr::str_squish() -> faculty_name 
  #Including xpath = "./text()" because the html_text2() function picked up html comments included in the source files with the names. Claude said that (xpath = "./text()" will allow the function to only pick out text, and exclude comments.
  
  name_links |> rvest::html_attr("href") -> faculty_website
  webpage |> rvest::html_elements("td:last-child i") |> rvest::html_text2() |> stringr::str_squish() -> faculty_position
  
  df = data.frame(department = utils::URLdecode(abbrv), 
                  faculty_name = faculty_name, 
                  faculty_position = faculty_position, 
                  faculty_website = faculty_website)
  Sys.sleep(1)
  return(df)
  
}

directory_df = purrr::map_df(.x = dept_names, .f = scrape_fsb_directory)

head(directory_df)
```


