---
title: "airbnb_analysis"
author: "Jacob Farmer"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
con = DBI::dbConnect(RSQLite::SQLite(), "../data/midwest_airbnb_extended.db")
listings     = DBI::dbReadTable(con, "listings") |> tibble::as_tibble()
availability = DBI::dbReadTable(con, "availability_monthly") |> tibble::as_tibble()
reviews      = DBI::dbReadTable(con, "reviews_monthly") |> tibble::as_tibble()
DBI::dbDisconnect(con)
```

## Task 1
```{r}
host_counts <- listings |> 
  dplyr::group_by(host_id) |> 
  dplyr::summarise(host_listings = dplyr::n())

listings <- listings |> 
  dplyr::left_join(host_counts, by = "host_id")

A1 <- host_counts |> 
  dplyr::filter(host_listings >= 10) |> 
  nrow()

A1

A2 <- listings |> 
  dplyr::filter(city == "Chicago") |> 
  dplyr::summarise(pct_superhosts = mean(host_listings>= 10) * 100)

A2
```


## Task 2
```{r}
listings_filtered <- listings |> 
  dplyr::filter(room_type == "Entire home/apt", 
                accommodates >= 4,
                number_of_reviews >= 10,
                review_scores_rating >= 4.8) |> 
  dplyr::mutate(price_per_person = price / accommodates)

median_listings <- listings_filtered |> 
  dplyr::group_by(city, neighbourhood) |> 
  dplyr::summarise(n = dplyr::n(),
                   median_price_per_person = median(price_per_person),
                   .groups = "drop_last") |>
  dplyr::filter(city == "Columbus",
                n >= 20)
  
A3 <- median_listings[which.min(median_listings$median_price_per_person), ]

A3
```

## Task 3
```{r}
estimated_revenue <- listings |> 
  dplyr::group_by(city, room_type) |> 
  dplyr::summarise(dplyr::across(c(price, reviews_per_month, estimated_revenue_l365d),
                                 ~ median(.x, na.rm = TRUE)),
                   .groups = "drop_last")

A4 <- estimated_revenue |> 
  dplyr::filter(city == "Twin Cities",
                room_type == "Entire home/apt") |> 
  dplyr::select(estimated_revenue_l365d)

A4
```

## Task 4
```{r}
top10_est_revenue <- listings |> 
  dplyr::group_by(city) |> 
  dplyr::arrange(dplyr::desc(estimated_revenue_l365d), .by_group = TRUE) |> 
  dplyr::mutate(top_10 = dplyr::row_number() <= ceiling(0.10 * dplyr::n())) |> 
  dplyr::summarise(pct_top_10 = sum(estimated_revenue_l365d[top_10]) /
                                sum(estimated_revenue_l365d) * 100)

A5 <- top10_est_revenue |> 
  dplyr::filter(city == "Columbus")

A5
```

## Task 5
```{r}
october <- availability |> 
  dplyr::filter(month == "2026-10")

october_homes <- listings |> 
  dplyr::filter(room_type == "Entire home/apt") |> 
  dplyr::left_join(october, by = "id") |> 
  dplyr::mutate(mostly_taken = nights_available < 0.5 * nights_in_month)

taken_share <- october_homes |> 
  dplyr::group_by(city) |> 
  dplyr::summarise(share_taken = mean(mostly_taken, na.rm = TRUE)) |> 
  dplyr::arrange(share_taken)

A <- taken_share |> 
  dplyr::slice_min(share_taken)
A6 <- A[1]

share_taken_pct <- A[2] * 100
A7 <- share_taken_pct

A6
A7
```

## Task 6
```{r}
monthly_reviews <- reviews |> 
  dplyr::left_join(listings |> dplyr::select(id, city), by = "id") |> 
  dplyr::filter(month >= "2025-07", month <= "2026-06") |> 
  dplyr::group_by(city, month) |> 
  dplyr::summarise(total_reviews = sum(reviews), .groups = "drop")

twin_cities <- monthly_reviews |> 
  dplyr::filter(city == "Twin Cities") |> 
  dplyr::arrange(dplyr::desc(total_reviews))

A8 <- twin_cities |> 
  dplyr::slice_max(total_reviews)

A8

A9 <- twin_cities |> 
  dplyr::summarise(ratio = max(total_reviews) / min(total_reviews))

A9
```

## Task 8
```{r}
no_availability <- listings |> 
  dplyr::anti_join(availability, by = "id")

A10 <- nrow(no_availability)

A10

no_availability |> 
  dplyr::count(city, sort = TRUE)

```

## Task 7
```{r}
superhost_medians <- listings |>
  dplyr::filter(room_type == "Entire home/apt") |> 
  dplyr::group_by(city, host_is_superhost) |>
  dplyr::summarise(median_price = median(price, na.rm = TRUE), 
                 median_rating = median(review_scores_rating, na.rm = TRUE),
                 median_rpm = median(reviews_per_month, na.rm = TRUE),
                 .groups = "drop_last")

superhost_medians

superhost_premiums <- superhost_medians |> 
  dplyr::group_by(city) |> 
  dplyr::summarise(premium = median_price[host_is_superhost == "t"] -
                             median_price[host_is_superhost == "f"])

superhost_premiums
```


